#################################################
# APPLICATION INFORMATION
#################################################

# Name of the application
spring.application.name=kabutar-backend

# Server port where backend will run
server.port=8080



#################################################
# DATABASE CONFIGURATION (PostgreSQL)
#################################################

# JDBC URL for PostgreSQL database
spring.datasource.url=jdbc:postgresql://kabutar-db.crowo0caudl8.eu-north-1.rds.amazonaws.com:5432/kabutar_db
										

# Database username
spring.datasource.username=kabutar

# Database password (CHANGE IN PRODUCTION)
spring.datasource.password=kabutar123

# PostgreSQL driver
spring.datasource.driver-class-name=org.postgresql.Driver



#################################################
# HIBERNATE / JPA CONFIGURATION
#################################################

# Automatically update database schema
# Safe for development. In production use "validate"
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in console
spring.jpa.show-sql=true

# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false
#################################################
# CONNECTION POOL (HikariCP)
#################################################

# Maximum connections allowed in pool
spring.datasource.hikari.maximum-pool-size=10

# Minimum idle connections
spring.datasource.hikari.minimum-idle=5

# Connection idle timeout (milliseconds)
spring.datasource.hikari.idle-timeout=30000

# Maximum lifetime of connection
spring.datasource.hikari.max-lifetime=1800000



#################################################
# JWT CONFIGURATION
#################################################

# Secret key used to sign JWT tokens
# CHANGE THIS TO A STRONG RANDOM STRING
jwt.secret=kabutar_super_secret_key_change_this

# Token expiration time (milliseconds)
# 24 hours
jwt.expiration=86400000



#################################################
# LOGGING CONFIGURATION
#################################################

# Show SQL queries
logging.level.org.hibernate.SQL=DEBUG

# Show parameter values
logging.level.org.hibernate.type.descriptor.sql=TRACE

# Security debug logs
logging.level.org.springframework.security=DEBUG



#################################################
# WEBSOCKET CONFIGURATION
#################################################

# Enable websocket message broker
spring.websocket.message-broker.enabled=true



#################################################
# SECURITY SETTINGS
#################################################

# Disable default security password
spring.security.user.name=disabled
spring.security.user.password=disabled